# Generated by Django 5.2.17 on 2026-08-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ledger',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
