# Generated by Django 5.2.17 on 2026-08-29 06:58

import noether.ledger.models_base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, validators=[noether.ledger.models_base.validate_slug]),
        ),
        migrations.AddField(
            model_name='ledger',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, validators=[noether.ledger.models_base.validate_slug]),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('ledger', 'slug'), name='unique_account_slug_per_ledger'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_ledger_slug'),
        ),
    ]
